FROM nginx:latest

# Kopiowanie pliku konfiguracyjnego Nginx do katalogu /etc/nginx/conf.d/
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Kopiowanie pliku index.php do katalogu /var/www/html/
COPY ./php/index.php /var/www/html/index.php
